package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class AccountRoleEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.user_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.role_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account_role.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.id
     *
     * @return the value of sys_account_role.id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.id
     *
     * @param id the value for sys_account_role.id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.user_id
     *
     * @return the value of sys_account_role.user_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.user_id
     *
     * @param userId the value for sys_account_role.user_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.role_id
     *
     * @return the value of sys_account_role.role_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.role_id
     *
     * @param roleId the value for sys_account_role.role_id
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.create_by
     *
     * @return the value of sys_account_role.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.create_by
     *
     * @param createBy the value for sys_account_role.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.create_time
     *
     * @return the value of sys_account_role.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.create_time
     *
     * @param createTime the value for sys_account_role.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.update_by
     *
     * @return the value of sys_account_role.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.update_by
     *
     * @param updateBy the value for sys_account_role.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account_role.update_time
     *
     * @return the value of sys_account_role.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account_role.update_time
     *
     * @param updateTime the value for sys_account_role.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:22 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}