package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class EmpCertApplyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.emp_id
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.idcard_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private String idcardImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.certificate_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private String certificateImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.idcard_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private String idcardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.cetificate_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private String cetificateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.create_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.create_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.update_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_cert_apply.update_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.emp_id
     *
     * @return the value of emp_cert_apply.emp_id
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.emp_id
     *
     * @param empId the value for emp_cert_apply.emp_id
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.idcard_images
     *
     * @return the value of emp_cert_apply.idcard_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public String getIdcardImages() {
        return idcardImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.idcard_images
     *
     * @param idcardImages the value for emp_cert_apply.idcard_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setIdcardImages(String idcardImages) {
        this.idcardImages = idcardImages == null ? null : idcardImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.certificate_images
     *
     * @return the value of emp_cert_apply.certificate_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public String getCertificateImages() {
        return certificateImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.certificate_images
     *
     * @param certificateImages the value for emp_cert_apply.certificate_images
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setCertificateImages(String certificateImages) {
        this.certificateImages = certificateImages == null ? null : certificateImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.idcard_status
     *
     * @return the value of emp_cert_apply.idcard_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public String getIdcardStatus() {
        return idcardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.idcard_status
     *
     * @param idcardStatus the value for emp_cert_apply.idcard_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setIdcardStatus(String idcardStatus) {
        this.idcardStatus = idcardStatus == null ? null : idcardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.cetificate_status
     *
     * @return the value of emp_cert_apply.cetificate_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public String getCetificateStatus() {
        return cetificateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.cetificate_status
     *
     * @param cetificateStatus the value for emp_cert_apply.cetificate_status
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setCetificateStatus(String cetificateStatus) {
        this.cetificateStatus = cetificateStatus == null ? null : cetificateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.create_by
     *
     * @return the value of emp_cert_apply.create_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.create_by
     *
     * @param createBy the value for emp_cert_apply.create_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.create_time
     *
     * @return the value of emp_cert_apply.create_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.create_time
     *
     * @param createTime the value for emp_cert_apply.create_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.update_by
     *
     * @return the value of emp_cert_apply.update_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.update_by
     *
     * @param updateBy the value for emp_cert_apply.update_by
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_cert_apply.update_time
     *
     * @return the value of emp_cert_apply.update_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_cert_apply.update_time
     *
     * @param updateTime the value for emp_cert_apply.update_time
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}