package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class EmpOrderEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.emp_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.status
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.remark
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.id
     *
     * @return the value of emp_order.id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.id
     *
     * @param id the value for emp_order.id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.emp_id
     *
     * @return the value of emp_order.emp_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.emp_id
     *
     * @param empId the value for emp_order.emp_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.order_id
     *
     * @return the value of emp_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.order_id
     *
     * @param orderId the value for emp_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.status
     *
     * @return the value of emp_order.status
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.status
     *
     * @param status the value for emp_order.status
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.remark
     *
     * @return the value of emp_order.remark
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.remark
     *
     * @param remark the value for emp_order.remark
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.create_time
     *
     * @return the value of emp_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.create_time
     *
     * @param createTime the value for emp_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.create_by
     *
     * @return the value of emp_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.create_by
     *
     * @param createBy the value for emp_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.update_time
     *
     * @return the value of emp_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.update_time
     *
     * @param updateTime the value for emp_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_order.update_by
     *
     * @return the value of emp_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_order.update_by
     *
     * @param updateBy the value for emp_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}