package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class EmpProfileEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.emp_id
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.level
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.idcard_number
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private String idcardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.idcard_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private String idcardImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.certificate_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private String certificateImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.status
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.create_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.create_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.update_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_profile.update_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.emp_id
     *
     * @return the value of emp_profile.emp_id
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.emp_id
     *
     * @param empId the value for emp_profile.emp_id
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.level
     *
     * @return the value of emp_profile.level
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.level
     *
     * @param level the value for emp_profile.level
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.idcard_number
     *
     * @return the value of emp_profile.idcard_number
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.idcard_number
     *
     * @param idcardNumber the value for emp_profile.idcard_number
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.idcard_images
     *
     * @return the value of emp_profile.idcard_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public String getIdcardImages() {
        return idcardImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.idcard_images
     *
     * @param idcardImages the value for emp_profile.idcard_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setIdcardImages(String idcardImages) {
        this.idcardImages = idcardImages == null ? null : idcardImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.certificate_images
     *
     * @return the value of emp_profile.certificate_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public String getCertificateImages() {
        return certificateImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.certificate_images
     *
     * @param certificateImages the value for emp_profile.certificate_images
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setCertificateImages(String certificateImages) {
        this.certificateImages = certificateImages == null ? null : certificateImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.status
     *
     * @return the value of emp_profile.status
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.status
     *
     * @param status the value for emp_profile.status
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.create_time
     *
     * @return the value of emp_profile.create_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.create_time
     *
     * @param createTime the value for emp_profile.create_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.create_by
     *
     * @return the value of emp_profile.create_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.create_by
     *
     * @param createBy the value for emp_profile.create_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.update_time
     *
     * @return the value of emp_profile.update_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.update_time
     *
     * @param updateTime the value for emp_profile.update_time
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_profile.update_by
     *
     * @return the value of emp_profile.update_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_profile.update_by
     *
     * @param updateBy the value for emp_profile.update_by
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}