package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class EmpSummaryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.emp_id
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.credit_total
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long creditTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.credit_remain
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long creditRemain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.order_quantity_done
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long orderQuantityDone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.order_quantity_serving
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long orderQuantityServing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.create_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.create_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.update_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_summary.update_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.emp_id
     *
     * @return the value of emp_summary.emp_id
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.emp_id
     *
     * @param empId the value for emp_summary.emp_id
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.credit_total
     *
     * @return the value of emp_summary.credit_total
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getCreditTotal() {
        return creditTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.credit_total
     *
     * @param creditTotal the value for emp_summary.credit_total
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setCreditTotal(Long creditTotal) {
        this.creditTotal = creditTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.credit_remain
     *
     * @return the value of emp_summary.credit_remain
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getCreditRemain() {
        return creditRemain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.credit_remain
     *
     * @param creditRemain the value for emp_summary.credit_remain
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setCreditRemain(Long creditRemain) {
        this.creditRemain = creditRemain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.order_quantity_done
     *
     * @return the value of emp_summary.order_quantity_done
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getOrderQuantityDone() {
        return orderQuantityDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.order_quantity_done
     *
     * @param orderQuantityDone the value for emp_summary.order_quantity_done
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setOrderQuantityDone(Long orderQuantityDone) {
        this.orderQuantityDone = orderQuantityDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.order_quantity_serving
     *
     * @return the value of emp_summary.order_quantity_serving
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getOrderQuantityServing() {
        return orderQuantityServing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.order_quantity_serving
     *
     * @param orderQuantityServing the value for emp_summary.order_quantity_serving
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setOrderQuantityServing(Long orderQuantityServing) {
        this.orderQuantityServing = orderQuantityServing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.create_time
     *
     * @return the value of emp_summary.create_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.create_time
     *
     * @param createTime the value for emp_summary.create_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.create_by
     *
     * @return the value of emp_summary.create_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.create_by
     *
     * @param createBy the value for emp_summary.create_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.update_time
     *
     * @return the value of emp_summary.update_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.update_time
     *
     * @param updateTime the value for emp_summary.update_time
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_summary.update_by
     *
     * @return the value of emp_summary.update_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_summary.update_by
     *
     * @param updateBy the value for emp_summary.update_by
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}