package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OfferApplyEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.id
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.name
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.phone
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.locations
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String locations;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.offers
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String offers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.remark
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.status
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.create_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.create_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.update_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offer_apply.update_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.id
     *
     * @return the value of offer_apply.id
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.id
     *
     * @param id the value for offer_apply.id
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.name
     *
     * @return the value of offer_apply.name
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.name
     *
     * @param name the value for offer_apply.name
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.phone
     *
     * @return the value of offer_apply.phone
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.phone
     *
     * @param phone the value for offer_apply.phone
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.locations
     *
     * @return the value of offer_apply.locations
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getLocations() {
        return locations;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.locations
     *
     * @param locations the value for offer_apply.locations
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setLocations(String locations) {
        this.locations = locations == null ? null : locations.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.offers
     *
     * @return the value of offer_apply.offers
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getOffers() {
        return offers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.offers
     *
     * @param offers the value for offer_apply.offers
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setOffers(String offers) {
        this.offers = offers == null ? null : offers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.remark
     *
     * @return the value of offer_apply.remark
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.remark
     *
     * @param remark the value for offer_apply.remark
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.status
     *
     * @return the value of offer_apply.status
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.status
     *
     * @param status the value for offer_apply.status
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.create_time
     *
     * @return the value of offer_apply.create_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.create_time
     *
     * @param createTime the value for offer_apply.create_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.create_by
     *
     * @return the value of offer_apply.create_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.create_by
     *
     * @param createBy the value for offer_apply.create_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.update_time
     *
     * @return the value of offer_apply.update_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.update_time
     *
     * @param updateTime the value for offer_apply.update_time
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offer_apply.update_by
     *
     * @return the value of offer_apply.update_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offer_apply.update_by
     *
     * @param updateBy the value for offer_apply.update_by
     *
     * @mbg.generated Wed Feb 13 12:15:48 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}