package com.octopus.taxcube.eds.entity;

public class OperOrderEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.operator_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long operatorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.order_id
     *
     * @return the value of oper_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.order_id
     *
     * @param orderId the value for oper_order.order_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.operator_id
     *
     * @return the value of oper_order.operator_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.operator_id
     *
     * @param operatorId the value for oper_order.operator_id
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }
}