package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OperOrderEntity extends OperOrderEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oper_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.create_by
     *
     * @return the value of oper_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.create_by
     *
     * @param createBy the value for oper_order.create_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.create_time
     *
     * @return the value of oper_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.create_time
     *
     * @param createTime the value for oper_order.create_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.update_by
     *
     * @return the value of oper_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.update_by
     *
     * @param updateBy the value for oper_order.update_by
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oper_order.update_time
     *
     * @return the value of oper_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oper_order.update_time
     *
     * @param updateTime the value for oper_order.update_time
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}