package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OrderIntervalEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_interval.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_interval.refresh_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Date refreshTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_interval.order_id
     *
     * @return the value of order_trace_interval.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_interval.order_id
     *
     * @param orderId the value for order_trace_interval.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_interval.refresh_time
     *
     * @return the value of order_trace_interval.refresh_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Date getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_interval.refresh_time
     *
     * @param refreshTime the value for order_trace_interval.refresh_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setRefreshTime(Date refreshTime) {
        this.refreshTime = refreshTime;
    }
}