package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OrderDistributeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_distribute.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_distribute.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_distribute.emp_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_distribute.create_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_distribute.create_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Long createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_distribute.id
     *
     * @return the value of order_trace_distribute.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_distribute.id
     *
     * @param id the value for order_trace_distribute.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_distribute.order_id
     *
     * @return the value of order_trace_distribute.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_distribute.order_id
     *
     * @param orderId the value for order_trace_distribute.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_distribute.emp_id
     *
     * @return the value of order_trace_distribute.emp_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_distribute.emp_id
     *
     * @param empId the value for order_trace_distribute.emp_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_distribute.create_time
     *
     * @return the value of order_trace_distribute.create_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_distribute.create_time
     *
     * @param createTime the value for order_trace_distribute.create_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_distribute.create_by
     *
     * @return the value of order_trace_distribute.create_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_distribute.create_by
     *
     * @param createBy the value for order_trace_distribute.create_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
}