package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OrderPayEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.order_id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.pay_method
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private String payMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.pay_type
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.price
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.remark
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.pay_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.pay_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Long payBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.create_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_pay.create_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    private Long createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.id
     *
     * @return the value of order_trace_pay.id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.id
     *
     * @param id the value for order_trace_pay.id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.order_id
     *
     * @return the value of order_trace_pay.order_id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.order_id
     *
     * @param orderId the value for order_trace_pay.order_id
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.pay_method
     *
     * @return the value of order_trace_pay.pay_method
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.pay_method
     *
     * @param payMethod the value for order_trace_pay.pay_method
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.pay_type
     *
     * @return the value of order_trace_pay.pay_type
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.pay_type
     *
     * @param payType the value for order_trace_pay.pay_type
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.price
     *
     * @return the value of order_trace_pay.price
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.price
     *
     * @param price the value for order_trace_pay.price
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.remark
     *
     * @return the value of order_trace_pay.remark
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.remark
     *
     * @param remark the value for order_trace_pay.remark
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.pay_time
     *
     * @return the value of order_trace_pay.pay_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.pay_time
     *
     * @param payTime the value for order_trace_pay.pay_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.pay_by
     *
     * @return the value of order_trace_pay.pay_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Long getPayBy() {
        return payBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.pay_by
     *
     * @param payBy the value for order_trace_pay.pay_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setPayBy(Long payBy) {
        this.payBy = payBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.create_time
     *
     * @return the value of order_trace_pay.create_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.create_time
     *
     * @param createTime the value for order_trace_pay.create_time
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_pay.create_by
     *
     * @return the value of order_trace_pay.create_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_pay.create_by
     *
     * @param createBy the value for order_trace_pay.create_by
     *
     * @mbg.generated Thu Jan 24 18:39:14 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
}