package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OrderTaskEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.order_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.task_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.task_name
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.status
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.progress
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private String progress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.remark
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.create_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.create_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.update_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_task.update_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.id
     *
     * @return the value of order_trace_task.id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.id
     *
     * @param id the value for order_trace_task.id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.order_id
     *
     * @return the value of order_trace_task.order_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.order_id
     *
     * @param orderId the value for order_trace_task.order_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.task_id
     *
     * @return the value of order_trace_task.task_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.task_id
     *
     * @param taskId the value for order_trace_task.task_id
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.task_name
     *
     * @return the value of order_trace_task.task_name
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.task_name
     *
     * @param taskName the value for order_trace_task.task_name
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.status
     *
     * @return the value of order_trace_task.status
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.status
     *
     * @param status the value for order_trace_task.status
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.progress
     *
     * @return the value of order_trace_task.progress
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public String getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.progress
     *
     * @param progress the value for order_trace_task.progress
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setProgress(String progress) {
        this.progress = progress == null ? null : progress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.remark
     *
     * @return the value of order_trace_task.remark
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.remark
     *
     * @param remark the value for order_trace_task.remark
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.create_time
     *
     * @return the value of order_trace_task.create_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.create_time
     *
     * @param createTime the value for order_trace_task.create_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.create_by
     *
     * @return the value of order_trace_task.create_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.create_by
     *
     * @param createBy the value for order_trace_task.create_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.update_time
     *
     * @return the value of order_trace_task.update_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.update_time
     *
     * @param updateTime the value for order_trace_task.update_time
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_task.update_by
     *
     * @return the value of order_trace_task.update_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_task.update_by
     *
     * @param updateBy the value for order_trace_task.update_by
     *
     * @mbg.generated Thu Jan 24 17:20:31 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}