package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class OrderQuotationEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_quotation.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_quotation.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_quotation.price
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_quotation.quotation_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Long quotationBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trace_quotation.quotation_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    private Date quotationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_quotation.id
     *
     * @return the value of order_trace_quotation.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_quotation.id
     *
     * @param id the value for order_trace_quotation.id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_quotation.order_id
     *
     * @return the value of order_trace_quotation.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_quotation.order_id
     *
     * @param orderId the value for order_trace_quotation.order_id
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_quotation.price
     *
     * @return the value of order_trace_quotation.price
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_quotation.price
     *
     * @param price the value for order_trace_quotation.price
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_quotation.quotation_by
     *
     * @return the value of order_trace_quotation.quotation_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Long getQuotationBy() {
        return quotationBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_quotation.quotation_by
     *
     * @param quotationBy the value for order_trace_quotation.quotation_by
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setQuotationBy(Long quotationBy) {
        this.quotationBy = quotationBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trace_quotation.quotation_time
     *
     * @return the value of order_trace_quotation.quotation_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public Date getQuotationTime() {
        return quotationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trace_quotation.quotation_time
     *
     * @param quotationTime the value for order_trace_quotation.quotation_time
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    public void setQuotationTime(Date quotationTime) {
        this.quotationTime = quotationTime;
    }
}