package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class PermissionEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.menu_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private String menuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.menu_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.remarks
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.menu_code
     *
     * @return the value of sys_permission.menu_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.menu_code
     *
     * @param menuCode the value for sys_permission.menu_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.menu_name
     *
     * @return the value of sys_permission.menu_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.menu_name
     *
     * @param menuName the value for sys_permission.menu_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_code
     *
     * @return the value of sys_permission.permission_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_code
     *
     * @param permissionCode the value for sys_permission.permission_code
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.permission_name
     *
     * @return the value of sys_permission.permission_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.permission_name
     *
     * @param permissionName the value for sys_permission.permission_name
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.remarks
     *
     * @return the value of sys_permission.remarks
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.remarks
     *
     * @param remarks the value for sys_permission.remarks
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_by
     *
     * @return the value of sys_permission.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_by
     *
     * @param createBy the value for sys_permission.create_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_time
     *
     * @return the value of sys_permission.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_time
     *
     * @param createTime the value for sys_permission.create_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_by
     *
     * @return the value of sys_permission.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_by
     *
     * @param updateBy the value for sys_permission.update_by
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_time
     *
     * @return the value of sys_permission.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_time
     *
     * @param updateTime the value for sys_permission.update_time
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}