package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class PopularizationEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.popularize_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Long popularizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.popularized_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Long popularizedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.status
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.create_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.create_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.update_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column popularization.update_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.id
     *
     * @return the value of popularization.id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.id
     *
     * @param id the value for popularization.id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.popularize_id
     *
     * @return the value of popularization.popularize_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Long getPopularizeId() {
        return popularizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.popularize_id
     *
     * @param popularizeId the value for popularization.popularize_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setPopularizeId(Long popularizeId) {
        this.popularizeId = popularizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.popularized_id
     *
     * @return the value of popularization.popularized_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Long getPopularizedId() {
        return popularizedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.popularized_id
     *
     * @param popularizedId the value for popularization.popularized_id
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setPopularizedId(Long popularizedId) {
        this.popularizedId = popularizedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.status
     *
     * @return the value of popularization.status
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.status
     *
     * @param status the value for popularization.status
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.create_time
     *
     * @return the value of popularization.create_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.create_time
     *
     * @param createTime the value for popularization.create_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.create_by
     *
     * @return the value of popularization.create_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.create_by
     *
     * @param createBy the value for popularization.create_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.update_time
     *
     * @return the value of popularization.update_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.update_time
     *
     * @param updateTime the value for popularization.update_time
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column popularization.update_by
     *
     * @return the value of popularization.update_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column popularization.update_by
     *
     * @param updateBy the value for popularization.update_by
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}