package com.octopus.taxcube.eds.entity;

import java.util.Date;

public class ProdServiceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.name
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.title_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String titleImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.desc_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String descImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.price_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String priceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.desc_price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String descPrice;


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.credit_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String creditType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.catalog_id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Long catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.status
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.create_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.create_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.update_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod_service.update_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    private Long updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.id
     *
     * @return the value of prod_service.id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.id
     *
     * @param id the value for prod_service.id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.name
     *
     * @return the value of prod_service.name
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.name
     *
     * @param name the value for prod_service.name
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.title_image
     *
     * @return the value of prod_service.title_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getTitleImage() {
        return titleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.title_image
     *
     * @param titleImage the value for prod_service.title_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setTitleImage(String titleImage) {
        this.titleImage = titleImage == null ? null : titleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.desc_image
     *
     * @return the value of prod_service.desc_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getDescImage() {
        return descImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.desc_image
     *
     * @param descImage the value for prod_service.desc_image
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setDescImage(String descImage) {
        this.descImage = descImage == null ? null : descImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.price_type
     *
     * @return the value of prod_service.price_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getPriceType() {
        return priceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.price_type
     *
     * @param priceType the value for prod_service.price_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setPriceType(String priceType) {
        this.priceType = priceType == null ? null : priceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.price
     *
     * @return the value of prod_service.price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.price
     *
     * @param price the value for prod_service.price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.desc_price
     *
     * @return the value of prod_service.desc_price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getDescPrice() {
        return descPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.desc_price
     *
     * @param descPrice the value for prod_service.desc_price
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setDescPrice(String descPrice) {
        this.descPrice = descPrice == null ? null : descPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.credit_type
     *
     * @return the value of prod_service.credit_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getCreditType() {
        return creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.credit_type
     *
     * @param creditType the value for prod_service.credit_type
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setCreditType(String creditType) {
        this.creditType = creditType == null ? null : creditType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.catalog_id
     *
     * @return the value of prod_service.catalog_id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Long getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.catalog_id
     *
     * @param catalogId the value for prod_service.catalog_id
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.status
     *
     * @return the value of prod_service.status
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.status
     *
     * @param status the value for prod_service.status
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.create_time
     *
     * @return the value of prod_service.create_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.create_time
     *
     * @param createTime the value for prod_service.create_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.create_by
     *
     * @return the value of prod_service.create_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.create_by
     *
     * @param createBy the value for prod_service.create_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.update_time
     *
     * @return the value of prod_service.update_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.update_time
     *
     * @param updateTime the value for prod_service.update_time
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod_service.update_by
     *
     * @return the value of prod_service.update_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod_service.update_by
     *
     * @param updateBy the value for prod_service.update_by
     *
     * @mbg.generated Fri Jan 11 14:19:59 CST 2019
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }
}