package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.AccountRoleEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AccountRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int insert(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int insertSelective(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    AccountRoleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int updateByPrimaryKeySelective(AccountRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account_role
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int updateByPrimaryKey(AccountRoleEntity record);

    List<AccountRoleEntity> selectByUserId(@Param("userId") String userId);

    void deleteByUserIdAndRoleId(@Param("userId") Long userId, @Param("roleId") Long roleId);
}