package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.AccountEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AccountEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    int insert(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    int insertSelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    AccountEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    int updateByPrimaryKeySelective(AccountEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_account
     *
     * @mbg.generated Thu Jan 10 16:05:30 CST 2019
     */
    int updateByPrimaryKey(AccountEntity record);

    AccountEntity selectByPhone(String phone);

    AccountEntity selectByWxOpenId(@Param("openId") String openId);

    List<AccountEntity> selectUsersByRole(@Param("type") String accountType);

    List<AccountEntity> selectByIds(@Param("accountIds") List<Long> accountIds);

    List<AccountEntity> selectBySpecialOfferType(@Param("offerType") String offerType);
}