package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.CreditItemEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CreditItemEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    int insert(CreditItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    int insertSelective(CreditItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    CreditItemEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    int updateByPrimaryKeySelective(CreditItemEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_item
     *
     * @mbg.generated Sat Jan 19 10:58:42 CST 2019
     */
    int updateByPrimaryKey(CreditItemEntity record);

    List<CreditItemEntity> selectByAccountId(@Param("accountId") Long accountId);

    CreditItemEntity selectBySourceId(@Param("sourceId") Long sourceId);

    Long selectTotalCreditByAccountId(@Param("accountId") Long accountId);

    CreditItemEntity selectBySourceIdAndReason(@Param("sourceId") Long sourceId,@Param("reason") String reason);
}