package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.CreditExchangeEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CreditExchangeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    int insert(CreditExchangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    int insertSelective(CreditExchangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    CreditExchangeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    int updateByPrimaryKeySelective(CreditExchangeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_exchange
     *
     * @mbg.generated Sat Jan 19 15:52:08 CST 2019
     */
    int updateByPrimaryKey(CreditExchangeEntity record);

    List<CreditExchangeEntity> selectAll();

    List<CreditExchangeEntity> selectByStatus(@Param("status") String status);
}