package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EmpCertApplyEntity;
import org.springframework.stereotype.Repository;

@Repository
public interface EmpCertApplyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    int deleteByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    int insert(EmpCertApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    int insertSelective(EmpCertApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    EmpCertApplyEntity selectByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    int updateByPrimaryKeySelective(EmpCertApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_cert_apply
     *
     * @mbg.generated Mon Jan 28 11:51:25 CST 2019
     */
    int updateByPrimaryKey(EmpCertApplyEntity record);
}