package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EmpOfferEntity;
import com.octopus.taxcube.eds.entity.EmpOfferEntityKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EmpOfferEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int deleteByPrimaryKey(EmpOfferEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int insert(EmpOfferEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int insertSelective(EmpOfferEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    EmpOfferEntity selectByPrimaryKey(EmpOfferEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int updateByPrimaryKeySelective(EmpOfferEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_offer
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int updateByPrimaryKey(EmpOfferEntity record);

    void batchInsert(List<EmpOfferEntity> empOfferEntities);

    List<EmpOfferEntity> selectByEmpId(@Param("empId") Long empId);

    List<EmpOfferEntity> selectEnableOfferByEmpId(@Param("empId") Long empId);

    List<EmpOfferEntity> selectByProdIdAndLocationAndStatus(@Param("prodId") Long prodId,@Param("location") String location,@Param("status") String status);
}