package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EmpOrderEntity;
import org.springframework.stereotype.Repository;

@Repository
public interface EmpOrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    int insert(EmpOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    int insertSelective(EmpOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    EmpOrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    int updateByPrimaryKeySelective(EmpOrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_order
     *
     * @mbg.generated Tue Feb 12 20:33:58 CST 2019
     */
    int updateByPrimaryKey(EmpOrderEntity record);
}