package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EmpProfileEntity;
import org.springframework.stereotype.Repository;

@Repository
public interface EmpProfileEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int deleteByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int insert(EmpProfileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int insertSelective(EmpProfileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    EmpProfileEntity selectByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int updateByPrimaryKeySelective(EmpProfileEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_profile
     *
     * @mbg.generated Tue Jan 15 18:51:04 CST 2019
     */
    int updateByPrimaryKey(EmpProfileEntity record);
}