package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EmpSummaryEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EmpSummaryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    int deleteByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    int insert(EmpSummaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    int insertSelective(EmpSummaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    EmpSummaryEntity selectByPrimaryKey(Long empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    int updateByPrimaryKeySelective(EmpSummaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_summary
     *
     * @mbg.generated Mon Jan 28 11:14:11 CST 2019
     */
    int updateByPrimaryKey(EmpSummaryEntity record);

    List<EmpSummaryEntity> selectByEmpIds(@Param("empIds") List<Long> empIds);
}