package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.EnterpriseInfoEntity;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface EnterpriseInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    int insert(EnterpriseInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    int insertSelective(EnterpriseInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    EnterpriseInfoEntity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    int updateByPrimaryKeySelective(EnterpriseInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_info
     *
     * @mbg.generated Tue Feb 12 11:46:24 CST 2019
     */
    int updateByPrimaryKey(EnterpriseInfoEntity record);

    List<EnterpriseInfoEntity> selectByStatus(String status);
}