package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.OfferApplyEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public interface OfferApplyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    int insert(OfferApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    int insertSelective(OfferApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    OfferApplyEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    int updateByPrimaryKeySelective(OfferApplyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offer_apply
     *
     * @mbg.generated Tue Jan 15 16:26:54 CST 2019
     */
    int updateByPrimaryKey(OfferApplyEntity record);

    List<OfferApplyEntity> selectByApplierId(@Param("applierId") Long userId);

    List<OfferApplyEntity> selectByStatus(@Param("status") String status);
}