package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.OrderIntervalEntity;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderIntervalEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insert(OrderIntervalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insertSelective(OrderIntervalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    OrderIntervalEntity selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKeySelective(OrderIntervalEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_interval
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKey(OrderIntervalEntity record);
}