package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.OrderCheckEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderCheckEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insert(OrderCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insertSelective(OrderCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    OrderCheckEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKeySelective(OrderCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_check
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKey(OrderCheckEntity record);

    List<OrderCheckEntity> selectCheckByOrderIds(@Param("orderIds") List<String> orderIds);
}