package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.OrderDistributeEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderDistributeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insert(OrderDistributeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insertSelective(OrderDistributeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    OrderDistributeEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDistributeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_distribute
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKey(OrderDistributeEntity record);

    List<OrderDistributeEntity> selectOrderDistributionByOrderIds(@Param("orderIds") List<String> orderIds);
}