package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.OrderQuotationEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderQuotationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insert(OrderQuotationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int insertSelective(OrderQuotationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    OrderQuotationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKeySelective(OrderQuotationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_trace_quotation
     *
     * @mbg.generated Thu Jan 24 12:38:26 CST 2019
     */
    int updateByPrimaryKey(OrderQuotationEntity record);

    List<OrderQuotationEntity> selectOrderQuotationByOrderIds(@Param("orderIds") List<String> orderIds);
}