package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.PopularizationEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PopularizationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    int insert(PopularizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    int insertSelective(PopularizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    PopularizationEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    int updateByPrimaryKeySelective(PopularizationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table popularization
     *
     * @mbg.generated Mon Jan 21 15:27:15 CST 2019
     */
    int updateByPrimaryKey(PopularizationEntity record);

    PopularizationEntity selectByPopularizedId(@Param("popularizedId") Long popularizedId);

    List<PopularizationEntity> selectAll();

    List<PopularizationEntity> selectByStatus(@Param("status") String status);
}