package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.ProdTaskEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProdTaskEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int insert(ProdTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int insertSelective(ProdTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    ProdTaskEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int updateByPrimaryKeySelective(ProdTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_task
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int updateByPrimaryKey(ProdTaskEntity record);

    List<ProdTaskEntity> selectByProdId(@Param("prodId") Long prodId);
}