package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.ProdServiceEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProdServiceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int insert(ProdServiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int insertSelective(ProdServiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    ProdServiceEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int updateByPrimaryKeySelective(ProdServiceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod_service
     *
     * @mbg.generated Fri Jan 11 13:34:16 CST 2019
     */
    int updateByPrimaryKey(ProdServiceEntity record);

    List<ProdServiceEntity> selectAll();

    List<ProdServiceEntity> selectByIds(@Param("prodIds") List<Long> prodIds);
}