package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.RolePermissionEntity;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

@Repository
public interface RolePermissionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int insert(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int insertSelective(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    RolePermissionEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int updateByPrimaryKeySelective(RolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Tue Feb 12 17:25:23 CST 2019
     */
    int updateByPrimaryKey(RolePermissionEntity record);

    List<RolePermissionEntity> selectByRoleId(@Param("roleId") String roleId);

    List<RolePermissionEntity> selectByRoleIds(@Param("roleIds") List<Long> roleIds);

    void deleteByRoleId(@Param("roleId") Long roleId);
}