package com.octopus.taxcube.eds.dao;

import com.octopus.taxcube.eds.entity.SysLogEntity;
import org.springframework.stereotype.Repository;

@Repository
public interface SysLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    int insert(SysLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    int insertSelective(SysLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    SysLogEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    int updateByPrimaryKeySelective(SysLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbg.generated Wed Jan 16 17:57:07 CST 2019
     */
    int updateByPrimaryKey(SysLogEntity record);
}